### ISSUE TITLE
Thank you for making this

### ISSUE THREAD

**Issue by Moon3Point14** [skoperst/deadly-dave#2]
I was looking for a perfect clone of Dave to make a meme with the inter-level "Good Luck! Only X more to go!" message. Building with SDL2 on Windows was bit difficult, but now I know how to do that.

Basically it showed an error

```
game.c: In function 'start_gameloop':
game.c:792:59: warning: format '%ld' expects argument of type 'long int', but argument 4 has type 'uint64_t' {aka 'long long unsigned int'} [-Wformat=]
             snprintf(level_path, 4096, "res/levels/level%ld.ddt", game->level);
```

which I fixed by typecasting `game->level` to `(long)game->level`

and also

```
C:/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o):crt0_c.c:(.text.startup+0x2e): undefined reference to 'WinMain'
collect2.exe: error: ld returned 1 exit status
mingw32-make: *** [Makefile:14: all] Error 1
```

This one was a bit tricky. I had to change the main() to remove the command line arguments, but that would not match the prototype declared in SDL_main().

I had to fix it by adding `#define SDL_MAIN_HANDLED` before `#include<SDL.h>`

**Also I found a bug in the game:**

When finishing a level, it literally says "Good Luck! Only X more to go!" instead of the number of levels remaining. Please fix that.
Thanks again.

**Comment by skoperst** [comment]
Hey, thanks for trying this out in Windows.

I fixed the 'X more to go' and the warning.
However I don't fully understand what you suggested regarding fixing the main(). 

Is it just about adding the `#define SDL_MAIN_HANDLED`?

**Comment by Moon3Point14** [comment]
I figured that it was because when main() is called with command line arguments, it's viewed as a console application and not as a Win32 GUI application. But simply changing `main(int argc, char* argv[])` to `main()` would result in this error:

```
game.c: In function 'SDL_main':
game.c:835:1: error: number of arguments doesn't match prototype
 int main() {
 ^~~
In file included from C:/SDL2/include/SDL2/SDL.h:32,
                 from game.c:8:
C:/SDL2/include/SDL2/SDL_main.h:121:29: error: prototype declaration
 extern SDLMAIN_DECLSPEC int SDL_main(int argc, char *argv[]);
                             ^~~~~~~~
mingw32-make: *** [Makefile:14: all] Error 1
```
So I googled how to avoid that and found adding `#define SDL_MAIN_HANDLED` before including SDL.h will fix that.

Then also, afterwards I found that adding -mwindows to compile flags will remove the trailing console window that's running while the game is launched.

Edit:

This is the error that would show up before chainging to `main()`:

```
C:/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o):crt0_c.c:(.text.startup+0x2e): undefined reference to `WinMain'
collect2.exe: error: ld returned 1 exit status
mingw32-make: *** [Makefile:14: all] Error 1
```

Edit2:

Turns out I don't have to change the declaration of `main()` to fix the problem. Just adding `#define SDL_MAIN_HANDLED` would fix the problem.

**Comment by skoperst** [comment]
Gotcha. Thanks for the explanation.
I will add `#define SDL_MAIN_HANDLED` and 'SDL_SetMainReady' as advised here: https://wiki.libsdl.org/SDL_SetMainReady.

By the way, next time you could send a pull-request.

**Comment by skoperst** [comment]
Fixed: https://github.com/skoperst/deadly-dave/commit/ca9598b9e2dba79537f021f0ad2325599b67d877
